# Generated by Django 2.0.6 on 2018-06-18 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20180617_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
