# Generated by Django 2.0.6 on 2018-06-29 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20180629_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
