# Generated by Django 2.0.6 on 2018-06-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20180629_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='user_created',
            field=models.CharField(max_length=150),
        ),
    ]
