# Generated by Django 2.0.6 on 2018-06-29 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_auto_20180629_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='user_created',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
